inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - Gemfile.lock
    - '**/*.md'
    - 'bin/console'
    - 'config/boot.rb'
    - vendor/**/*

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false
