inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - Gemfile.lock
    - '**/*.md'
    - 'bin/console'
    - 'config/boot.rb'
